sudo: require
dist: bionic
language: generic
jdk: openjdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake 
      - libfabric-dev
      - build-essential
      - libboost-dev
      - libboost-system-dev
      - openjdk-8-jdk
      - maven

install:
  - mkdir build
  - cd build
  - cmake -DWITH_JAVA=on ..

before_script: make
script:
  - ctest
  - cd ../java/hpnl
  - mvn package
  - mvn clean
  - cd ../../build
after_script: make clean
